on: 
  push:
  workflow_dispatch:
  
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'http://gitea.hafuhafu.cn/StoneShiLei/test.git'
          GIT_USERNAME: StoneShiLei
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
